- include: raspbian.yaml
  when: "ansible_lsb.id == 'Raspbian'"

- include: debian.yaml
  when: "ansible_os_family == 'Debian' and not ansible_lsb.id == 'Raspbian'"

- include: rhel.yaml
  when: "ansible_os_family == 'RedHat'"

#- name: Reload systemd
#  yum:
#    daemon_reload: true
#  when: ansible_service_mgr == "systemd"
#  changed_when: false

- name: Reload systemd
  shell: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"
  changed_when: false

