- name: Create update flag
  file:
    state: touch
    path: /var/lib/ansible/flags/package-update.flag

- name: Restart services
  service:
    name: '{{ item }}'
    state: restarted
  with_items: services

- name: Reload services
  service:
    name: '{{ item }}'
    state: reloaded
  with_items: services
